---
linters-settings:
  misspell:
    locale: US
  funlen:
    lines: 80
    statements: 60
  gocognit:
    min-complexity: 26

linters:
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - dupl
    - errcheck
    - errname
    - errorlint
    - funlen
    - gocognit
    - goconst
    - gosec
    - ineffassign
    - misspell
    - prealloc
    - unconvert

issues:
  exclude-rules:
    - path: _test.go
      linters:
        - dupl
        - funlen
        - gocognit
        - goconst
  exclude:
    - "ExampleOrderList refers to unknown identifier: OrderList"
