# SPDX-FileCopyrightText: 2022 Weston Schmidt <weston_schmidt@alumni.purdue.edu>
# SPDX-License-Identifier: Apache-2.0
---
name: 'Dependabot auto approvals'

on:
  pull_request_target:
  schedule:
    - cron: '28 22 * * 6'

permissions:
  pull-requests: write
  contents: write

jobs:
  package:
    uses: goschtalt/.github/.github/workflows/approve-dependabot.yml@aab94edb7e3a0dd5b8cc0b0ef0208e3bbd312b23
    secrets: inherit
