# SPDX-FileCopyrightText: 2022 Weston Schmidt <weston_schmidt@alumni.purdue.edu>
# SPDX-License-Identifier: Apache-2.0
---
name: 'Dependabot auto approvals'

on:
  pull_request_target:

permissions:
  pull-requests: write
  contents: write

jobs:
  package:
    uses: goschtalt/.github/.github/workflows/approve-dependabot.yml@ccce4870ac5feb2abf112bc94773bda9d8de92cb # v1.2.7
    secrets: inherit
